config/routes.rb
Rails.application.routes.draw do
  resources :sessions, only: [:new, :create, :destroy]
  get 'signup', to: 'logins#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  resources :logins

  get 'page/index'

  get 'ratings/index'

  get 'ratings/new'

  get 'ratings/edit'

  get 'ratings/show'

  resources :admins

  resources :users

  resources :admins
  resources :options
  get 'admins/login'

   get 'questions/answerpage'

    post 'questions/answerpage'

    post 'surveys/new'

  resources :questions

  root 'surveys#new'

   resources :surveys do
    resources :users
  end
end

app/models/answer.rb
class Answer < ActiveRecord::Base
	
end

app/models/login.rb
class Login < ActiveRecord::Base
  has_secure_password
  
  validates :first_name,
            presence: true
  validates :last_name,
            presence: true
  validates :email,
            presence: true,
            uniqueness: true,
            format: {
              with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
            }
  def to_s
    "#{first_name} #{last_name}"
  end
end

app/models/question.rb
class Question < ActiveRecord::Base
	has_many :surveys
	validates_presence_of :quest
		
end

app/models/survey.rb
class Survey < ActiveRecord::Base
  belongs_to :question
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
	validate  :mob 
	has_many :surveys
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  private
  def current_login
    Login.where(id: session[:login_id]).first
  end
  helper_method :current_login
end

app/controllers/logins_controller.rb
class LoginsController < ApplicationController
  before_action :set_login, only: [:show, :edit, :update, :destroy]

  # GET /logins
  # GET /logins.json
  def index
    @logins = Login.all
  end

  # GET /logins/1
  # GET /logins/1.json
  def show
  end

  # GET /logins/new
  def new
    @login = Login.new
  end

  # GET /logins/1/edit
  def edit
  end

  # POST /logins
  # POST /logins.json
  def create
    @login = Login.new(login_params)

    respond_to do |format|
      if @login.save
        format.html { redirect_to @login, notice: 'Login was successfully created.' }
        format.json { render :show, status: :created, location: @login }
      else
        format.html { render :new }
        format.json { render json: @login.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /logins/1
  # PATCH/PUT /logins/1.json
  def update
    respond_to do |format|
      if @login.update(login_params)
        format.html { redirect_to @login, notice: 'Login was successfully updated.' }
        format.json { render :show, status: :ok, location: @login }
      else
        format.html { render :edit }
        format.json { render json: @login.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /logins/1
  # DELETE /logins/1.json
  def destroy
    @login.destroy
    respond_to do |format|
      format.html { redirect_to logins_url, notice: 'Login was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_login
      @login = Login.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def login_params
      params.require(:login).permit(:first_name, :last_name, :email, :password, :password_confirmation)
    end
end

app/controllers/page_controller.rb
class PageController < ApplicationController
  def index
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
 def index
  	@question=Question.all
  end

  def new
  	@question =Question.new
  #  render json: @question
  end

  def create
    
  	params.permit!
  	@question =Question.new(params[:question])
  	if @question.save
  		redirect_to :action => 'index'
  	else
      render 'new'
      
  	end
  end

  def destroy
  	@question =Question.find(params[:id])
  	@question.delete
    redirect_to :action => "index"
 end 

  def edit
  	@question=Question.find(params[:id])
  end



  def update
    params.permit!
    @question=Question.find(params[:id])
    if @question.update_attributes(params[:question])
       redirect_to :action => "index"
       
     else
      render "edit"
    end
  end

  def answerpage
  	@question = Question.all
  end

  


  def show
  end

  private
  def question_params
  	params.require(:question).permit
  end
end

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController
  def index
  end

  def new
  end

  def edit
  end

  def show
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  	 login = Login.find_by_email(params[:email])
    if login && login.authenticate(params[:password])
      session[:login_id] = login.id
      redirect_to root_url, notice: 'Logged in!'
    else
      render :new
    end
  end

  def destroy
  	session[:login_id] = nil
    redirect_to root_url, notice: 'Logged out!'
  end
  
end

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController
  def index
  	@survey =Survey.all
    @user = User.all
  end

  def new
  	@questions = Question.all
    @survey = Survey.new
  end

  def create
    

  #@survey =Survey.new(params[:survey_params])
   #if @survey.save

    # redirect_to :action => 'index'

    #else
     #render 'new'
     #params[:questions] = params[:questions].to_i
#@survey =Survey.new(params[:survey_params])
 #   if @question.id.save
  #    redirect_to :action => 'index'
   # else
    #  render 'new'
    #end
  #end

  params[:survey][:questions].each do |s|
    survey =Survey.new
    survey.question_id = s[0]
    survey.options = s[1]
    survey.user_id = session[:id]
    survey.name = session[:name]
    survey.save
  end  
  render :action => 'index'
  #render json:params[:survey][:questions]

  
    


end

#@survey =Survey.new(params[:survey_params])
 #   if @survey.save
#
 #     redirect_to :action => 'index'

  #  else
   #   render 'new'
    #  params[:questions] = params[:questions].to_i
  def edit
  end

  def show

  end

  private
  
  def survey_params
  	params.require(:survey).permit(:name)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  #before_action :set_user, only: [:show,:edit,:update,:destroy]
  def index

  	@user =User.all
  end

  def new
  	@user=User.new
  end

  def create
  	params.permit!
  	@user =User.new(params[:user])

  		 @user.save

  		 
       session[:name] =  @user.name
       session[:id] = @user.id
       session[:dob]= @user.dob
        session[:id] = @user.id
        session[:mob]= @user.mob
        session[:id] = @user.id
        
        redirect_to new_survey_path
  			#format.html {redirect_to @user, notice: 'user is created successfully '}

     #else

     	#render 'new'
     #end

end


  def edit
  end

  def show
  end
   private
   def user_params
     params.require(:user).permit
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/logins_helper.rb
module LoginsHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/surveys_helper.rb
module SurveysHelper
	
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/logins/_form.html.erb
<%= form_for(@login) do |f| %>
  <% if @login.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@login.errors.count, "error") %> prohibited this login from being saved:</h2>

      <ul>
      <% @login.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/logins/edit.html.erb
<h1>Editing Login</h1>

<%= render 'form' %>

<%= link_to 'Show', @login %> |
<%= link_to 'Back', logins_path %>

app/views/logins/index.html.erb
 <p id="notice"><%= notice %></p>

<h1>Listing Logins</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @logins.each do |login| %>
      <tr>
        <td><%= login.first_name %></td>
        <td><%= login.last_name %></td>
        <td><%= login.email %></td>
        <td><%= link_to 'Show', login %></td>
        <td><%= link_to 'Edit', edit_login_path(login) %></td>
        <td><%= link_to 'Destroy', login, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<%= link_to 'New Login', new_login_path %> 

app/views/logins/new.html.erb
<h1>New Login</h1>

<%= render 'form' %>

<%= link_to 'Back', logins_path %>

app/views/logins/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @login.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @login.last_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @login.email %>
</p>

<%= link_to 'Edit', edit_login_path(@login) %> |
<%= link_to 'Back', logins_path %>

app/views/questions/_error_page.html.erb
<% if @question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@question.errors.count, "error") %> prohibited this user from being saved:</h2>
      <ul>
      <% @question.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
<% end %> 

app/views/questions/_form.html.erb
<script src="/assets/questions/new.js"></script>



<%= render "error_page"%>

<center><h4>Admin Page </h4>
<%= image_tag("images.jpg", :alt => "rails image") %>



<table>
	<%= form_for @question do | question | %>
		<tr>
			<td><%= question.label :"question:" %> </td>

			<td><%= question.text_field :quest,:hint => "Question should be ended with question mark"%> </td>
			<td><button type="button" onclick="myFunction();">?</button></td>

			<script type="text/javascript">
				function myFunction() {
				    alert("Please enter question with question mark");
				}
			</script>
		</tr>

		<br>
		<td><%= question.label :"option1:" ,class: 'control-label col-sm-1'%> </td>
		<td><%= question.text_field :option1, class: 'form-control'%> </td>
		</tr>
		</tr>
		
		<br>
		<td><%= question.label :"option2:" %> </td>
		<td><%= question.text_field :option2 %> </td>
		</tr>
		</tr>

		<br>
		<td><%= question.label :"option3:"  %> </td>
		<td><%= question.text_field :option3 %> </td>
		</tr>
		<br>
		<td><%= question.label :"option4:"  %> </td>
		<td><%= question.text_field :option4 %> </td>
		</tr>
		<br>
		<td><%= question.label :"option5:" %> </td>
		<td><%= question.text_field :option5 %> </td>
		</tr>

		<tr>
		<center><td><%= question.submit "ADD" , class: "btn"%> </td></center>

<td><%= question.submit "Update" %></td>
      
		</tr></center>

	<%end%>
</table>

app/views/questions/edit.html.erb
<%= render "form"%>

<%= link_to "Home", questions_path%>

app/views/questions/index.html.erb
<table border="1"style="width:100%">
	<tr>
     
		<th>Questions</th>
		<th>option1</th>
		<th>option2</th>
		<th>option3</th>
		<th>option4</th>
		<th>option5</th>


		
	 </tr>
	 
	<% @question.each do |f|%>
	<tr>
		<td><%= f.quest %></td>
		<td><%= f.option1 %></td>
		<td><%= f.option2 %></td>
		<td><%= f.option3 %></td>
		<td><%= f.option4 %></td>
		<td><%= f.option5 %></td>
		<td><%= link_to "Edit", edit_question_path(f)%></td>
		<td><%= link_to "Delete", f, :method=>"delete", :data=>{:confirm=>"Are you sure!"}%></td>
		</tr>
   <%end%>
	
	
</table>
<%= link_to "back" , new_question_path %>
<%= link_to "clientpage",new_survey_path %>

app/views/questions/new.html.erb
<%= link_to "Take Survey", new_user_path%>
<!%= link_to "New user", new_admin_path%>

<%= render "form"%>
<center><!%=  button_to("Anspage", { action: "answerpage"}, class: "question")  %></center>

app/views/questions/show.html.erb
<h1>Questions#show</h1>
<p>Find me in app/views/questions/show.html.erb</p>

app/views/ratings/edit.html.erb
<h1>Ratings#edit</h1>
<p>Find me in app/views/ratings/edit.html.erb</p>

app/views/ratings/index.html.erb
<h1>Ratings#index</h1>
<p>Find me in app/views/ratings/index.html.erb</p>

app/views/ratings/new.html.erb
<h1>Ratings#new</h1>
<p>Find me in app/views/ratings/new.html.erb</p>

app/views/ratings/show.html.erb
<h1>Ratings#show</h1>
<p>Find me in app/views/ratings/show.html.erb</p>

app/views/surveys/edit.html.erb
<h1>Surveys#edit</h1>
<p>Find me in app/views/surveys/edit.html.erb</p>

app/views/surveys/new.html.erb
<center><h3>SF-12® Health Survey Scoring Demonstration<h3></center>

<right><strong>Hi <%=session[:name]%>
<br>MobileNo: <%=session[:mob]%>
<br>DateOfBirth: <%=session[:dob]%></strong></right>
<CENTER>This survey asks for your views about your health. 
This information will help you keep track of how you feel and how well you are able to do your usual activities.

Answer every question by selecting the answer as indicated. 
If you are unsure about how to answer a question, please give the best answer you can.</CENTER>

<%= link_to "New user" , new_user_path %>
<%= link_to 'Take Survey' , new_survey_path %>
<hr>
<div id="login_header">
 <% if current_login %>
Logged in as <%= current_login.email %>.
 <%= link_to "Log Out", logout_path %>
 <% else %>
 <%= link_to "Sign Up", signup_path %> or
 <%= link_to "Log In", login_path %>
 <% end %>
</div>
<% flash.each do |key, value| %>
 <%= content_tag(:div, class: "alert alert-#{key}") do %>
<p><%= value %></p>
 <% end %>
<% end %>
<!------- form tag-------------------------->
<%= form_for(@survey) do |f| %>
	<% @questions.each do |question| %>
		<%= question.quest %><br>
		<ul><%= radio_button_tag("survey[questions][#{question.id}]", question.option1)%><%=question.option1%><br>
		<%= radio_button_tag("survey[questions][#{question.id}]", question.option2)%><%=question.option2%><br>
		<%= radio_button_tag("survey[questions][#{question.id}]", question.option3)%><%=question.option3%><br>
		<%= radio_button_tag("survey[questions][#{question.id}]", question.option4)%><%=question.option4%><br>
		<%= radio_button_tag("survey[questions][#{question.id}]", question.option5)%><%=question.option5%><br></ul>
		<hr>
		<% end %>
		
	<center><%=  f.submit "save form"  %></center>
<% end %><br>
  <hr>
     
	
<hr>


  <center><%=  button_to("Reset Form", { action: "new"}, class: "survey")  %></center>
 
  <center><h5>Thank you for completing these questions!</h5></center>


 <div>
 <div class="survey" text-center>



</div>

  </div>

app/views/surveys/show.html.erb
<h1>Surveys#show</h1>
<p>Find me in app/views/surveys/show.html.erb</p>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/index.html.erb
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
       </tr>
        <tr>
      <th>Dob</th>
      <th colspan="3"></th>
       </tr>
        <tr>
      <th>Mob</th>
      <th colspan="3"></th>
       </tr>
  </thead>

  <tbody>
  <% @user.each do | user | %>

  <tr>
  <td> <%= user.name %> </td>
  <td> <%= user.dob %> </td>
  <td> <%= user.mob %> </td>
  </tr>
  <%end%>
  </tbody>
  </table>

  <%= link_to 'New user' , new_user_path %>

app/views/users/new.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do | message | %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
  <table>
  <tr>
  <td>
    <%= f.label :username %><td>
    <td><%= f.text_field :name %></td>

    <td><%= f.label :Dob %></td>
    <td><%= f.date_field :dob %></td>

    <td><%= f.label :MobNo %></td>
    <td><%= f.text_field :mob %></td>
    </table>
  </div>
  
  
  <div class="actions">
    <%= f.submit "submit",class: "btn" %>
  </div>
<% end %>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>